### ISSUE TITLE
Use `slam.hound/swap-in-reconstructed-ns-form` for reconstruction

### ISSUE THREAD

**Issue by guns** [chadhq/slamhound-lt#1]
Hello,

I'd love to link to this plugin in the Slamhound README, but I think it would be nice if the LT plugin offered the same "reconstruct in place" function as the Emacs and Vim plugins.

This can be done quite easily using Slamhound's command line entry function:

``` clojure
(binding [clojure.pprint/*print-right-margin* buffer-text-width]
  (let [file (java.io.File. "path/to/current/file")]
    (slam.hound/swap-in-reconstructed-ns-form file)))
```

The `*print-right-margin*` binding is optional, but the clojure.pprint
default of 72 chars is a little narrow for my taste.

Thanks!

EDIT:

I changed the recommendation from slam.hound/-main to slam.hound/swap-in-reconstructed-ns-form; I forgot that the extra error messages with the latter would be helpful for debugging.

**Comment by chadhq** [comment]
Hello,

Thanks for writing. I have a 'reconstruct in place' to test it out locally, but I did that manually. I'll change it over to your suggestion and update my plugin this evening. I'll send you a message when I've pushed the update.

Quite excited that you want to include it in the Slamhoud README, Let me know if there is anything else I can do.

Thanks again!

**Comment by chadhq** [comment]
Done!

Just pushed v0.0.3 which just replaces the namespace in place.

Thanks again!

**Comment by guns** [comment]
Okay, I've added the link. Thanks for developing this plugin!
